### ISSUE TITLE
KeyError "database" in self._remote_databag

### ISSUE THREAD

**Issue by gboutry** [canonical/mysql-router-k8s-operator#78]
## Steps to reproduce
Here's a full deployment:
1. Deploy this terraform plan: https://github.com/gboutry/sunbeam-terraform/tree/feat/impl-mysql-router (don't worry about Horizon in error state, there is a fix in the edge channel to make it work with router)

## Expected behavior
MySQL Router comes online without having transient error state

## Actual behavior

MySQL Router comes online only after having gone through some error state
```
unit-nova-cell-mysql-router-0: 10:43:43 ERROR unit.nova-cell-mysql-router/0.juju-log backend-database:64: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/./src/charm.py", line 259, in <module>
    ops.main.main(MySQLRouterOperatorCharm)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 946, in _on_relation_changed_event
    self.on.database_created.emit(event.relation, app=event.app, unit=event.unit)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/./src/charm.py", line 217, in reconcile_database_relations
    self.database_provides.reconcile_users(
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/src/relations/database_provides.py", line 180, in reconcile_users
    relation.create_database_and_user(router_endpoint=router_endpoint, shell=shell)
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/src/relations/database_provides.py", line 97, in create_database_and_user
    username=username, database=self._database
  File "/var/lib/juju/agents/unit-nova-cell-mysql-router-0/charm/src/relations/database_provides.py", line 54, in _database
    return self._remote_databag["database"]
KeyError: 'database'
```

## Versions

Operating system: `Ubuntu 22.04.2 LTS`

Juju CLI: `3.2-rc1-genericlinux-amd64`

Juju agent: `3.2-RC1`

mysql-k8s charm revision: 82
mysql-router-k8s charm revision: 35

microk8s: `MicroK8s v1.26.4 revision 5222`

## Log output
<details>
<summary> juju debug-log --replay </summary>

Full output is too long for github comment, here's the pastebin:
https://pastebin.ubuntu.com/p/pCZHKrn7YH/
</details>

## Additional context

When trying to reproduce this behavior on a model with fewer applications, I didn't see errors. I don't know if it's related.

**Comment by gboutry** [comment]
Thank you @carlcsaposs-canonical, I've been unable to reproduce the error using `8.0/edge/pr-75`
