### ISSUE TITLE
Failed to bootstrap router

### ISSUE THREAD

**Issue by gboutry** [canonical/mysql-router-k8s-operator#85]
## Steps to reproduce
1. Deploy https://github.com/gboutry/sunbeam-terraform/tree/feat/impl-mysql-router

I've seen this error only once, so not sure it can be reproduced

## Expected behavior
No errors

## Actual behavior

```
023-05-30T10:39:53.4360873Z unit-horizon-mysql-router-0: 10:39:37 ERROR unit.horizon-mysql-router/0.juju-log Failed to bootstrap router
2023-05-30T10:39:53.4361610Z logged_command=['mysqlrouter', '--bootstrap', 'relation-65:***@mysql-primary.openstack.svc.cluster.local:3306', '--strict', '--user', 'mysql', '--conf-set-option', 'http_server.bind_address=127.0.0.1', '--conf-use-gr-notifications']
2023-05-30T10:39:53.4361710Z stderr:
2023-05-30T10:39:53.4362199Z Error: It appears that a router instance named 'system' has been previously configured in this host. If that instance no longer exists, use the --force option to overwrite it.

2023-05-30T10:39:53.4363948Z unit-horizon-mysql-router-0: 10:39:37 ERROR unit.horizon-mysql-router/0.juju-log Uncaught exception while in charm code:
2023-05-30T10:39:53.4364078Z Traceback (most recent call last):
2023-05-30T10:39:53.4364424Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/./src/charm.py", line 252, in <module>
2023-05-30T10:39:53.4364585Z     ops.main.main(MySQLRouterOperatorCharm)
2023-05-30T10:39:53.4364908Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/venv/ops/main.py", line 441, in main
2023-05-30T10:39:53.4365061Z     _emit_charm_event(charm, dispatcher.event_name)
2023-05-30T10:39:53.4365419Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
2023-05-30T10:39:53.4365542Z     event_to_emit.emit(*args, **kwargs)
2023-05-30T10:39:53.4365885Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/venv/ops/framework.py", line 354, in emit
2023-05-30T10:39:53.4365997Z     framework._emit(event)
2023-05-30T10:39:53.4366342Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/venv/ops/framework.py", line 830, in _emit
2023-05-30T10:39:53.4366456Z     self._reemit(event_path)
2023-05-30T10:39:53.4366789Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/venv/ops/framework.py", line 919, in _reemit
2023-05-30T10:39:53.4366898Z     custom_handler(event)
2023-05-30T10:39:53.4367392Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/./src/charm.py", line 244, in _on_mysql_router_pebble_ready
2023-05-30T10:39:53.4367525Z     self.reconcile_database_relations()
2023-05-30T10:39:53.4367905Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/./src/charm.py", line 223, in reconcile_database_relations
2023-05-30T10:39:53.4368103Z     workload_.enable(tls=self.tls.certificate_saved, unit_name=self.unit.name)
2023-05-30T10:39:53.4368433Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/src/workload.py", line 244, in enable
2023-05-30T10:39:53.4368557Z     self._bootstrap_router(tls=tls)
2023-05-30T10:39:53.4368896Z   File "/var/lib/juju/agents/unit-horizon-mysql-router-0/charm/src/workload.py", line 214, in _bootstrap_router
2023-05-30T10:39:53.4369261Z     raise Exception("Failed to bootstrap router") from None
2023-05-30T10:39:53.4369463Z Exception: Failed to bootstrap router
```

## Versions

Operating system: Ubuntu 22.04.2 LTS

Juju CLI: 3.2-beta3-genericlinux-amd64

Juju agent: 3.2-beta3

mysql-k8s charm revision: 83
mysql-router-k8s charm revision: 39 

microk8s: MicroK8s v1.26.4 revision 5222

## Log output
<details>
<summary> juju debug-log --replay </summary>
Uploaded to issue because it's too big
[6_Collect juju status.txt](https://github.com/canonical/mysql-router-k8s-operator/files/11599378/6_Collect.juju.status.txt)
</details>

## Additional context

10 Routers are deployed, 9 were deployed fine, only 1 had the issue

**Comment by gboutry** [comment]
Well, this happened during a github action run, and no other application show a restart or something similar.

The github action step consists of:
```shell
terraform init
terraform apply -auto-approve
juju model-config -m openstack automatically-retry-hooks=true
juju-wait -vw -m openstack -t 3600 -x cinder-ceph -r 3
```

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical  re: upgrade-charm event is fired on pod delete.
Discussed those findings with @zmraul in Prague, see https://discourse.charmhub.io/t/event-upgrade-charm/6485/5
Undocumented "feature" :-D
